version: '3.8'

services:
  orchestrator:
    container_name: orchestrator
    image: mongo:4.4
    networks:
      - mongo-network
    volumes:
      - ./scripts/start-replica-set.sh:/scripts/start-replica-set.sh
      - ./scripts/mongo-init.js:/scripts/mongo-init.js
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    links:
      - mongo1
      - mongo2
      - mongo3
    restart: on-failure
    entrypoint: ['./scripts/start-replica-set.sh']

  mongo1:
    container_name: mongo1
    image: mongo:4.4
    networks:
      - mongo-network
    ports:
      - 27017:27017
    depends_on:
      - mongo2
      - mongo3
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs"]
  mongo2:
    container_name: mongo2
    image: mongo:4.4
    networks:
      - mongo-network
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    networks:
      - mongo-network
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

networks:
  mongo-network:
    driver: bridge
